version: '3'

services:

  catalog-service:
    build: ./catalog-service
    ports:
      - "3001:3001"

  order-service:
    build: ./order-service
    ports:
      - "3002:3002"
    depends_on:
      - catalog-service

  frontend-service:
    build: ./frontend-service
    ports:
      - "3000:3000"
    depends_on:
      - catalog-service
      - order-service